import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {JSDOM} from 'jsdom';
import * as core from '../demo-core.mjs';
const html=fs.readFileSync(new URL('../demos.html',import.meta.url),'utf8');const script=fs.readFileSync(new URL('../demos.js',import.meta.url),'utf8').replace(/^import[^\n]+\n/,'');
function setup(mode='booking',mobile=false){const dom=new JSDOM(html,{url:`http://localhost/demos.html?app=${mode}`,runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;Object.assign(w,core);w.matchMedia=()=>({matches:mobile});w.structuredClone=structuredClone;w.HTMLElement.prototype.scrollIntoView=function(){};w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'))};w.print=()=>{w.didPrint=true};w.eval(script + '\nwindow.__readState = () => data;');const q=s=>w.document.querySelector(s);const click=s=>{assert.ok(q(s),'missing selector '+s);q(s).click()};const input=(s,value,event='input')=>{assert.ok(q(s),'missing input '+s);q(s).value=value;q(s).dispatchEvent(new w.Event(event,{bubbles:true}))};const state=()=>w.__readState();return{dom,w,q,click,input,state,close:()=>w.close()};}
test('全3画面がデスクトップ・モバイル初期設定でエラーなく描画される',()=>{for(const mode of ['booking','approval','estimate'])for(const mobile of [false,true]){const t=setup(mode,mobile);assert.ok(t.q('h1').textContent.length);assert.ok(t.q('main'));assert.equal(t.q('#drawer').open,false);if(mode==='estimate')assert.match(t.q('#quote-total').textContent,/224,400/);if(mode==='booking'&&mobile)assert.ok(t.q('.agenda'));t.close();}});
test('予約フォームから登録→来店→施術完了しカルテに反映',()=>{const t=setup();t.click('[data-action="new-booking"]');t.click('[form="booking-form"]');assert.equal(t.state().bookings.length,8);assert.match(t.q('#drawer').textContent,/予約の詳細/);t.click('[data-action="arrive-booking"]');t.click('[data-action="complete-booking"]');assert.equal(t.state().customers.find(c=>c.id==='c4').visits,1);t.click('#drawer [data-action="customer-detail"]');t.input('#customer-form textarea','次回の施術メモを保存');t.click('[form="customer-form"]');assert.equal(t.state().customers.find(c=>c.id==='c4').note,'次回の施術メモを保存');t.close();});
test('重複予約エラーが表示され、入力を修正して登録できる',()=>{const t=setup();t.click('[data-action="new-booking"]');t.input('#booking-time','11:30','change');t.click('[form="booking-form"]');assert.match(t.q('#booking-error').textContent,/重な/);assert.equal(t.state().bookings.length,7);t.input('#booking-time','13:00','change');t.click('[form="booking-form"]');assert.equal(t.state().bookings.length,8);t.close();});
test('予約キャンセルは確認ダイアログを経て予定表から除外される',()=>{const t=setup();t.click('[data-action="booking-detail"][data-id="b4"]');t.click('[data-action="cancel-booking"]');assert.equal(t.state().bookings.find(b=>b.id==='b4').status,'confirmed');t.click('#confirm-yes');assert.equal(t.state().bookings.find(b=>b.id==='b4').status,'cancelled');assert.equal(t.q('[data-action="booking-detail"][data-id="b4"]'),null);t.close();});
test('領収書を開いて承認し、処理済み履歴から確認できる',()=>{const t=setup('approval',true);t.click('[data-action="expense-select"][data-id="EXP-024"]');assert.ok(t.q('.expense-workspace.show-detail'));t.click('[data-action="receipt"]');assert.match(t.q('#drawer').textContent,/18,000/);t.click('[data-action="close-drawer"]');t.click('#decision-form [value="approved"]');assert.equal(t.state().expenses.find(e=>e.id==='EXP-024').status,'approved');t.click('[data-action="expense-filter"][data-filter="approved"]');t.click('[data-action="expense-select"][data-id="EXP-024"]');assert.match(t.q('.expense-detail-panel').textContent,/承認を記録/);t.close();});
test('未添付申請の承認を阻止し、理由付き差戻しを記録',()=>{const t=setup('approval');t.click('[data-action="expense-select"][data-id="EXP-022"]');t.click('#decision-form [value="approved"]');assert.match(t.q('#decision-error').textContent,/未添付/);t.click('#decision-form [value="returned"]');assert.match(t.q('#decision-error').textContent,/理由/);t.input('#decision-comment','領収書を添付してください');t.click('#decision-form [value="returned"]');assert.equal(t.state().expenses.find(e=>e.id==='EXP-022').status,'returned');t.close();});
test('新規経費申請のフォームが承認待ちへ接続する',()=>{const t=setup('approval');t.click('[data-action="new-expense"]');t.click('[form="expense-form"]');assert.equal(t.state().expenses.length,6);assert.equal(t.state().expenses[0].status,'pending');assert.equal(t.state().expenses[0].receipt,true);t.close();});
test('検索の空状態と解除、顧客検索が使える',()=>{const t=setup('approval');t.input('#expense-search','存在しない申請');assert.match(t.q('.expense-list-panel').textContent,/該当する申請はありません/);t.input('#expense-search','');assert.ok(t.q('.expense-item'));t.click('[data-mode="booking"]');t.click('[data-action="view-customers"]');t.input('#customer-search','A01');assert.equal(t.w.document.querySelectorAll('.customer-card').length,1);t.close();});
test('見積明細の追加、数量変更、値引きが合計と書面に反映',()=>{const t=setup('estimate');t.input('[data-line="l1"] [data-linefield="quantity"]','4');assert.match(t.q('#quote-total').textContent,/279,400/);t.input('#quote-discount','4000');assert.match(t.q('#quote-total').textContent,/275,000/);t.click('[data-action="add-line"]');assert.equal(t.state().quotes[0].lines.length,4);t.click('[data-action="quote-preview"]');assert.match(t.q('.quote-paper').textContent,/275,000/);t.click('[data-action="print-quote"]');assert.equal(t.w.didPrint,true);assert.match(t.q('#print-root').textContent,/架空データ/);t.close();});
test('無効な見積を発行させず、修正→発行→複製の状態が連動',()=>{const t=setup('estimate');t.input('#quote-discount','999999');assert.match(t.q('#quote-error').textContent,/値引き/);t.click('[data-action="issue-quote"]');assert.equal(t.q('#confirm-dialog').open,false);t.input('#quote-discount','0');t.click('[data-action="issue-quote"]');t.click('#confirm-yes');assert.equal(t.state().quotes[0].status,'issued');t.click('[data-action="quote-edit"]');assert.equal(t.q('[data-qfield="client"]').disabled,true);t.click('[data-action="duplicate-quote"]');assert.equal(t.state().quotes.length,3);assert.equal(t.state().quotes[0].status,'draft');assert.equal(t.q('[data-qfield="client"]').disabled,false);t.close();});
test('ユーザー入力はHTMLとして実行されず文字列として表示される',()=>{const t=setup('estimate');t.input('[data-qfield="client"]','<img src=x onerror="alert(1)">');t.click('[data-action="quote-preview"]');assert.equal(t.q('.paper-client img'),null);assert.match(t.q('.paper-client').textContent,/<img/);t.close();});
test('リセットの取り消しはデータを保持し、確定は全デモを初期化する',()=>{const t=setup('estimate');t.click('[data-action="new-quote"]');t.click('[data-action="reset"]');t.click('#confirm-cancel');assert.equal(t.state().quotes.length,3);t.click('[data-action="reset"]');t.click('#confirm-yes');assert.equal(t.state().quotes.length,2);t.close();});
