import test from 'node:test';import assert from 'node:assert/strict';
import {initialState,saveBooking,transitionBooking,decideExpense,quoteTotals,issueQuote,shiftDate,csvCell} from '../demo-core.mjs';
const seed=()=>initialState('2026-09-08');
const input={customer:'c4',date:'2026-09-08',time:'13:00',staff:'haru',service:'cut',source:'電話',note:'テスト'};
test('予約を登録し、来店と施術完了でカルテが更新される',()=>{const s=seed(),b=saveBooking(s,input);assert.equal(s.bookings.length,8);transitionBooking(s,b.id,'arrived');transitionBooking(s,b.id,'done');assert.equal(s.customers.find(c=>c.id==='c4').visits,1);assert.equal(s.customers.find(c=>c.id==='c4').last,s.today);assert.throws(()=>transitionBooking(s,b.id,'done'));});
test('開始時刻が異なっても施術時間の重複を検出する',()=>{const s=seed();assert.throws(()=>saveBooking(s,{...input,time:'12:00'}),/重な/);assert.equal(s.bookings.length,7);});
test('施術終了と次の開始が同時なら予約できる',()=>{const s=seed();assert.doesNotThrow(()=>saveBooking(s,{...input,time:'12:30'}));});
test('予約を変更しても自分の予約枠と競合しない',()=>{const s=seed();const b=saveBooking(s,input);saveBooking(s,{...input,note:'変更'},b.id);assert.equal(s.bookings.length,8);assert.equal(b.note,'変更');});
test('キャンセルすると同じ枠へ予約できる',()=>{const s=seed();const b=saveBooking(s,input);transitionBooking(s,b.id,'cancelled');assert.doesNotThrow(()=>saveBooking(s,input));});
test('来店済み予約の変更・キャンセルを拒否する',()=>{const s=seed();assert.throws(()=>saveBooking(s,input,'b2'));assert.throws(()=>transitionBooking(s,'b2','cancelled'));});
test('翌日の予約の来店受付を拒否する',()=>{const s=seed();assert.throws(()=>transitionBooking(s,'b7','arrived'),/今日/);});
test('閉店を超える施術、営業時間外、不正な日付・担当者を拒否する',()=>{for(const patch of [{time:'18:30',service:'color'},{time:'08:30'},{time:'13:15'},{date:'2026-09-07'},{date:'2026-02-30'},{date:'invalid'},{staff:'unknown'},{customer:'unknown'}])assert.throws(()=>saveBooking(seed(),{...input,...patch}));});
test('領収書付き経費を承認し履歴を追加する',()=>{const s=seed(),e=decideExpense(s,'EXP-024','approved','確認済み');assert.equal(e.status,'approved');assert.equal(e.history.length,2);assert.throws(()=>decideExpense(s,e.id,'approved'));});
test('未添付の申請は承認を拒否し理由付き差戻しを許可する',()=>{const s=seed();assert.throws(()=>decideExpense(s,'EXP-022','approved'),/未添付/);assert.throws(()=>decideExpense(s,'EXP-022','returned','  '),/理由/);assert.equal(decideExpense(s,'EXP-022','returned','領収書を添付してください').status,'returned');});
test('複数明細・値引き・税の計算を検証する',()=>{const q=seed().quotes[0];assert.deepEqual(quoteTotals(q),{subtotal:204000,discount:0,taxable:204000,tax:20400,total:224400});q.discount=4000;q.tax=8;assert.equal(quoteTotals(q).total,216000);});
test('税の端数は課税対象額の集計後に切り捨てる',()=>{const q=seed().quotes[0];q.lines=[{name:'品目',quantity:1,price:109}];assert.equal(quoteTotals(q).tax,10);});
test('過大な値引き・負数・空明細・無効数量を拒否する',()=>{for(const patch of [{discount:204001},{discount:-1},{tax:9},{lines:[]},{lines:[{name:'品目',price:10,quantity:0}]},{lines:[{name:'品目',price:-1,quantity:1}]},{lines:[{name:'品目',price:NaN,quantity:1}]},{lines:[{name:'',price:100,quantity:1}]}])assert.throws(()=>quoteTotals({...seed().quotes[0],...patch}));});
test('発行前の宛先・日付チェックと発行後の二重処理拒否',()=>{const q=seed().quotes[0];q.valid='2026-09-01';assert.throws(()=>issueQuote(q));q.valid='2026-10-08';q.client='';assert.throws(()=>issueQuote(q));q.client='サンプル社';issueQuote(q);assert.equal(q.status,'issued');assert.throws(()=>issueQuote(q));});
test('CSVセルをクォートし数式としての実行を防ぐ',()=>{assert.equal(csvCell('=1+1'),'"\'=1+1"');assert.equal(csvCell('a"b'),'"a""b"');assert.equal(csvCell('a,b'),'"a,b"');});
test('日付移動は月と年をまたぐ',()=>{assert.equal(shiftDate('2026-12-31',1),'2027-01-01');assert.equal(shiftDate('2026-03-01',-1),'2026-02-28');});
